# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{zoopla}
  s.version = "0.1.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Evgeny Shadchnev"]
  s.date = %q{2011-03-03}
  s.description = %q{Access zoopla.co.uk API from ruby scripts. Fetch sales and rental properties for the UK}
  s.email = %q{evgeny.shadchnev@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.markdown"
  ]
  s.files = [
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.markdown",
    "Rakefile",
    "lib/zoopla.rb",
    "lib/zoopla/api.rb",
    "lib/zoopla/listings.rb",
    "lib/zoopla/listings/listing.rb",
    "lib/zoopla/listings/rentals.rb",
    "lib/zoopla/listings/sales.rb",
    "lib/zoopla/version.rb",
    "test/api_replies/big_request_page1.js",
    "test/api_replies/big_request_page2.js",
    "test/api_replies/postcode.js",
    "test/helper.rb",
    "test/test_zoopla_listings.rb",
    "zoopla.gemspec"
  ]
  s.homepage = %q{http://github.com/shadchnev/zoopla}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.5.2}
  s.summary = %q{Access zoopla.co.uk API from ruby scripts}
  s.test_files = [
    "test/helper.rb",
    "test/test_zoopla_listings.rb"
  ]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<hashie>, ["~> 1.0.0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<mocha>, ["~> 0.9.12"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_development_dependency(%q<rcov>, [">= 0.9.9"])
      s.add_development_dependency(%q<curb>, ["~> 0.7.12"])
      s.add_development_dependency(%q<json>, ["~> 1.4.3"])
    else
      s.add_dependency(%q<hashie>, ["~> 1.0.0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<mocha>, ["~> 0.9.12"])
      s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_dependency(%q<rcov>, [">= 0.9.9"])
      s.add_dependency(%q<curb>, ["~> 0.7.12"])
      s.add_dependency(%q<json>, ["~> 1.4.3"])
    end
  else
    s.add_dependency(%q<hashie>, ["~> 1.0.0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<mocha>, ["~> 0.9.12"])
    s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
    s.add_dependency(%q<rcov>, [">= 0.9.9"])
    s.add_dependency(%q<curb>, ["~> 0.7.12"])
    s.add_dependency(%q<json>, ["~> 1.4.3"])
  end
end

